#!/bin/bash

unset PAGE_CPU_SHARE PAGE_PLAN_POLICY PAGE_ROW_OFF
unset PAGE_FORCE_CPU PAGE_FORCE_HYBRID
unset PAGE_DUAL_X_DIAG PAGE_XPLACEMENT_DIAG PAGE_HTX_DIAG PAGE_THP_DIAG
unset PAGE_CONTENTION_DIAG PAGE_SAME_PART_DIAG PAGE_DEBUG_LB
unset PAGE_PLATFORM_PREFLIGHT_ONLY

export PAGE_EXEC_MODE=hybrid
export PAGE_CPU_BASELINE=halav_csr
export PAGE_DSP_INDEX=32
export PAGE_DSP_VALUES=auto
export PAGE_HYBRID_THREADS=16
export PAGE_DUAL_X_PROD=1
export PAGE_CPU_HYBRID_SIDE=0
export PAGE_CONT_REBALANCE=1
export PAGE_CSR_NUMA_PROD=1
export PAGE_FAST_PREP=1
export PAGE_FAST_SHADOW_PLAN=0
export PAGE_PACKED_X=1
export PAGE_PREFIX_CALIB=1
export PAGE_AUTOTUNE=0
export PAGE_VROW_G_GATE=1

export PAGE_ABLATE_VROW=0
export PAGE_ABLATE_SIGMA=0
export PAGE_ABLATE_MEMORY_PLACEMENT=0
